// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI8mHQo0ZGT-mYM0F86isPvpdeBc5u8yY',
    appId: '1:983635513077:web:a03a10bffee3990d50ffbc',
    messagingSenderId: '983635513077',
    projectId: 'ielts-listening-1f472',
    authDomain: 'ielts-listening-1f472.firebaseapp.com',
    storageBucket: 'ielts-listening-1f472.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqPD2rMyCmHb19cbzzqfucqMY27lyU1l0',
    appId: '1:983635513077:android:699e8da827b97bee50ffbc',
    messagingSenderId: '983635513077',
    projectId: 'ielts-listening-1f472',
    storageBucket: 'ielts-listening-1f472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKPo82dzMisrc8uRDfIvu5Y_ly3JzsFco',
    appId: '1:983635513077:ios:2c87d82a9d22ab8f50ffbc',
    messagingSenderId: '983635513077',
    projectId: 'ielts-listening-1f472',
    storageBucket: 'ielts-listening-1f472.firebasestorage.app',
    iosBundleId: 'com.example.ieltsListeningWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKPo82dzMisrc8uRDfIvu5Y_ly3JzsFco',
    appId: '1:983635513077:ios:2c87d82a9d22ab8f50ffbc',
    messagingSenderId: '983635513077',
    projectId: 'ielts-listening-1f472',
    storageBucket: 'ielts-listening-1f472.firebasestorage.app',
    iosBundleId: 'com.example.ieltsListeningWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI8mHQo0ZGT-mYM0F86isPvpdeBc5u8yY',
    appId: '1:983635513077:web:4f3e743954d13f8b50ffbc',
    messagingSenderId: '983635513077',
    projectId: 'ielts-listening-1f472',
    authDomain: 'ielts-listening-1f472.firebaseapp.com',
    storageBucket: 'ielts-listening-1f472.firebasestorage.app',
  );
}
